### ISSUE TITLE
Wrong time

### ISSUE THREAD

**Issue by carlhoerberg** [vend/phoneduty#2]
Installed the app via the Heroku deploy button. I've configured the correct timezone in my Pagerduty profile, but the endpoint reports that it's 4:29pm while the time here right now is 12:29pm.

**Comment by morganpyne** [comment]
Hi Carl! Thanks, yep it was a known issue with the PagerDuty API that I had opened a ticket with them about - basically they didn't return the timezone in a standard format which was easily parseable. I left it as it was because it worked enough for us but I can see that this is not a satisfactory solution for everyone. I'll see if I can 'fix' it properly, and if not, I'll remove it.

**Comment by morganpyne** [comment]
Fix now committed.

**Comment by carlhoerberg** [comment]
Thanks!
